apiVersion: v1
kind: Service
metadata:
  name: {{ include "reportportal.fullname" . }}-analyzer
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - name: headless
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: {{ include "reportportal.fullname" . }}-analyzer
  type: ClusterIP
